### ISSUE TITLE
Independent keyboard shortcut for "Skip to highlight"

### ISSUE THREAD

**Issue by NewsGuyTor** [ajayyy/SponsorBlock#1187]
I think a customizable keyboard shortcut for skipping to the highlight (if existing) should be implemented. 

That would make it much faster to skip there than to use the mouse.

**Comment by ajayyy** [comment]
Enter can be used for this

**Comment by NewsGuyTor** [comment]
That just skips and unskips intermissions and other segments before the highlight in my experience. Try to press enter [on this video](https://www.youtube.com/watch?v=-I-XCpRPREc) for example. 

A customizable keyboard shortcut would be much preferable even if enter worked flawlessly though. That way you could move to the highlight in less than a second after loading the video.

**Comment by ajayyy** [comment]
Yea, right now it is the same shortcut for highlight and segments, so if there is another segment that is also at the start, it will take priority

**Comment by ToanLish** [comment]
For people who use manual skipping to highlight, this is pretty much essential in my opinion.

**Comment by qgustavor** [comment]
Since the key bind is used for both actions, when both are available in some video it have to choose which action. There were some times that I was watching some video and thought "well, I don't have time for that, just skip to the highlight" and pressed enter, but since it was after a sponsor skip pressing enter returned to the sponsor segment and I had to click on the button instead of using the key bind. If you prefer keeping one key bind for both actions at least allow customizing the behavior when there's ambiguity.
