### ISSUE TITLE
Unclear dialog icon

### ISSUE THREAD

**Issue by RichyT** [ajayyy/SponsorBlock#1270]
In the list of segments, to the right of the thumbs up/thumbs down, there's a small icon that looks a bit like a clipboard action icon. When clicked, it spins. I have no idea what it's doing. It could possibly do with a tooltip or something. In fact, all the icons in the row could do with clarification although I was kinda able to work out what the others did (though thumbs up only seems to cancel thumbs down? Not sure about the eye).

https://uxmyths.com/post/715009009/myth-icons-enhance-usability

**Comment by mchangrh** [comment]
Text would be near impossible especially on videos with 40+ segments - tooltips would be more useful

Thumbs up - Upvote
Thumbs down - Downvote + Hide Segment
Clipboard - Copy segment UUID
Eye - Hide Segment

**Comment by RichyT** [comment]
Is the UUID of any use to the vast majority of users? I have no strong hate for it being there but it might be better only visible in some kind of dev mode?

The up/downvote thing is tricky. You can't remove a downvote by clicking the downvote again. Clicking the upvote appears to clear it but then it's not clear if you've just removed the downvote or if you've actually upvoted. Clicking the upvote a second time doesn't appear to do anything extra.

Anyway, that's kinda outside the scope of my original comment so I'll just leave it at that.

**Comment by mchangrh** [comment]
UUID is very helpful for reporting segments, especially if there are multiple segments on the same timestamp

and downvote/upvote is sent to the server - it's not supposed to be "removed" like a facebook like since it has a lot more weight to it - two downvotes will remove a segment and an upvote prioritizes it over other segments in the same time

they can't be persistent either since there is a possibility of overwriting your previous vote
