### ISSUE TITLE
[!] Do not submit new issues about submitting

### ISSUE THREAD

**Issue by Saiv46** [ajayyy/SponsorBlock#1549]
You had tried to upload new segments but you've encountered an error?
Do not submit new issue yet! Check existing issues first

### 5XX HTTP error
That means that server is down (#1546).
See [SponsorBlock Status](https://status.sponsor.ajay.app/), as in 20/10/2022 it's reporting **Major outage**.

### "Users have voted that new segments..."
All needed segments of category are already submitted by other users, but cache is not updated yet.
Please wait for 30 minutes or later before checking video and submitting missing segments again.

**Comment by mchangrh** [comment]
Another known "issues" is 

## Segments Disappearing after submittting
If you do not receive a 4xx/ 5xx error on submitting but they seem to just disappear and don't appear on reloads, the segments have been submitted, they are just behind a dumb cache that can't be cleared - check in in 30 minutes and they should be there.

**do not keep on submitting segments**

**Comment by h7896v7347** [comment]
I do not want to add a new topic, and this is partly related to 5xx errors.

Can you add an option to use backup servers when the main server returns 5xx. (reading segment information)

**Comment by joshinils** [comment]
do created segments which i could not upload get stored on my machine somewhere somehow?
can i look at a list of unsubmitted segments and the videos i created them for?
can i go back and edit those later?

**Comment by VictorWesterlund** [comment]
I find it puzzling that the server goes down so often given the amount active users against the amount of money this project receives per month through sponsors.

**Comment by mchangrh** [comment]
> I find it puzzling that the server goes down so often given the amount active users against the amount of money this project receives per month through sponsors.

we're not the mob, money don't automatically make problems go away 😂

**Comment by Quix0r** [comment]
As a new user, I wonder where I can get my username from or is this registration closed? When I try to set any username, I get `Username: A connection error has occurred. Error code: 404`

**Comment by VictorWesterlund** [comment]
> money don't automatically make problems go away

No, but it enables more infrastructure redundancy (load-balancing, backup servers etc.)

> segments which i could not upload get stored on my machine

and/or developer time to work around the issue on a software-level, this suggestion as an example.

---

![image](https://user-images.githubusercontent.com/35688133/197398418-69f37570-f051-46bb-89ce-8a6e2b17fc13.png)
I would not take pride in these kinds of uptimes even for an unfunded, maintained project; especially not if I want the community to keep supporting it monetarily and through user submissions.

Unfortunately no real competition exists for this extension - it will always be better than nothing until that changes :/

**Comment by ajayyy** [comment]
Demotivating the people working on the issue in their spam time is clearly the best solution 👍

thanks for you contribution

**Comment by VictorWesterlund** [comment]
Do you not agree this is a pretty big issue worth investigating?

Requesting additional funding, hiring maintainers to offload tasks or ***at least*** acknowledge this is a problem and it will take some (possibly a long) time to fix due to insufficient resources.

**Comment by ajayyy** [comment]
You are reading the acknowlegement of the problem my guy

**Comment by VictorWesterlund** [comment]
Does the project (and sponsors) not deserve more than "the server is down, tough luck"?

**Comment by ajayyy** [comment]
What do you want, me begging on my knees in forgiveness? I am litterally working on it right now.

If you did actually donate, which I doubt with your attitude, send me an email and I will give you a full refund.

**Comment by VictorWesterlund** [comment]
Sorry if my attitude sounds disrespectful,

My point is since this is a reoccurring issue with great frequency, a more detailed description of/reason for the issue would be prudent. That's all really.

If money is an issue I will gladly support this project since I find it very useful and would hate to see it go under. But please make that statement, right now it kind of looks like you acknowledge the issue yes, but don't consider it important enough to look into a long-term fix and just let it go down again tomorrow.

*"We know this is an issue but unfortunately due to X a fix will not land until Y. Please consider supporting the project through Patreon or by contributing to help expedite the process"* - or similar would go a long way to boost sponor-morale

**Comment by ajayyy** [comment]
There is very detailed info on discord/matrix  As I've said on numerous times, it's design problems and incompetence, not money

**Comment by VictorWesterlund** [comment]
I can only go by what I see and Discord is not mentioned to contain additional info here. Do you mind copying these details to GH so others may see it? 

Lots of people probably aren't in the Discord and just want to know the state of things at a glance.

**Comment by PeterDaveHello** [comment]
I believe that nobody here is trying to show a bad attitude but want to see this project become better and better, sometimes there are just misunderstanding, let's take it easy.

The stability and realiability is obiviously something need to be taken care of. @ajayyy is it possible that some details can also be shared on GitHub, so that people not hanging on Discord can also join the discussion, would also like to see how I can help(just sent a very small pull request to the server side project and got merged earlier).

Thanks for the effort creating and maintaining this project, let users and contributors know what kind of help is needed and how can we help, should make this project become more fantastic together :tada:

**Comment by magizhchi99** [comment]
> I think this convo is getting a little distracted, but here a tldr of the current state:

- current postgres stack has had many issues, is awful to deal with, has bad rollback support and doesn't handle seamless updates. In general, I want to get this switched over to something else, which is currently stackgres, which I am doing right now. right now I'm dealing with sb-server not hosting the server for some reason but I can debug that on my own

- the main issue in the past few days has been sb-server increasing in ram in  a very fast time period and crashing. Since these all crash at the same time, it creates a cascading failure with crashloopbackoff
   - there are many possible reasons for this, a build up of requests to something, maybe redis, maybe postgres. or something else is memory leaking. hopefully it is postgres and finishing the stackgres move will fix it.

- an issue exists where if a k8s node is using too much ram, it crashes and I have to manually restart it in hetzner's UI. This is now "fixed" by the previously mentioned workaround of making sure there is some room left after requests.

- redis is currently non persistent right now, and if it crashes, creates a 15 minute downtime while cache is refilled

- since redis is single threaded and only running in one instance right now, it is bottlecked at the max cpu it can use. This makes many redis requests take longer than they should.
  - I tried using a helm chart that creates a redis-cluster but was having issues with it crashing

- stats page requests are badly made and take too long. They should have more values precomputed in some way to properly restore the stats page

@VictorWesterlund

**Comment by VictorWesterlund** [comment]
That's an amazing summary, thank you!! Way more details than I expected.

Maybe @Saiv46 should link to @magizhchi99's reply from the OG post so others can find it quickly, since this issue is already pinned it should be the best place for it anyways.

Again, sorry for the attitude. I think that summary should ease the friction and boost incentive for people with the knowhow and time to contribute to do so.

**Comment by PabzRoz** [comment]
I haven't been able to submit anything in over a week. Just constant errors and server being down nonstop. I've been wasting more time getting errors trying to submit timestamps than I'm actually saving skipping any sponsors.

**Comment by ajayyy** [comment]
![Screenshot_20221024-023518_Discord](https://user-images.githubusercontent.com/12688112/197462495-2c9e7bf5-e7d5-4c2d-965c-3566def894a5.png)

**Comment by WoodpeckerBaby** [comment]
> There is very detailed info on discord/matrix if you want it. It's design problems and incompetence, not money

The Discord invite link on your website has expired. Can't join.

**Comment by dgw** [comment]
> > There is very detailed info on discord/matrix if you want it. It's design problems and incompetence, not money
> 
> The Discord invite link on your website has expired. Can't join.

Regardless of invite link freshness, placing status info behind an account signup form (both Discord and Matrix require an account to view any information in the respective SponsorBlock community) is my least favorite thing about the modern web.

Enabling previews on the Matrix instance might mitigate this a little? But ideally, status details would be posted on the status page and/or here in the public issue tracker that anyone can see, regardless of whether they have an account.

**Comment by ajayyy** [comment]
Matrix does not require account sign up

**Comment by dgw** [comment]
> Matrix does not require account sign up

I must be doing something wrong then, because when I try to join the Matrix room via Element I get this:

![image](https://user-images.githubusercontent.com/164140/197646478-fc4ac91d-6877-4d11-99af-1d58c7b72a41.png)

**Comment by ajayyy** [comment]
Element is bugged, I had to refresh it and change the url a few times before it worked

**Comment by war59312** [comment]
To help with this. Would be sweet if could specific a different submission server.

**Comment by Emalton** [comment]
Perhaps Ajay could start a GoFundMe or a bug bounty to entice people to help?
