### ISSUE TITLE
[Firefox] Page loads very slowly

### ISSUE THREAD

**Issue by SakhJack** [ajayyy/SponsorBlock#1748]
when opening new tab it takes anywhere from 5 to 20 seconds to load all page elements
video loads normally, but everything else lags behind
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10335530/236633185-68c362ac-6d6b-41ec-9e48-bf42f8747919.png)
</details>

***
this is what happens when reloading main page 
<details><summary>Screenshot</summary>

  ![image](https://user-images.githubusercontent.com/10335530/236633084-d821ad11-0767-48e0-b3b6-007ebf085c56.png)
</details>

***
this started happening yesterday
resetting settings to default does nothing
opening video in same tab doesn't have this problem
no other extensions are enabled
***
Browser: Firefox 112.0.2 (64 bit)
OS: Win10 21H2 19044

**Comment by ajayyy** [comment]
Can you send logs

**Comment by SakhJack** [comment]
ah nevermind, it was 3rd party JS that supposed to limit CPU usage
`https://greasyfork.org/en/scripts/418283-youtube-cpu-tamer`
not updated for 2 years, so probably doesn't work properly

**Comment by Synetech** [comment]
I tried that, but it doesn't work. Even without CPU Tamer (even without TamperMonkey enabled at all), SponsorBlock 5.4.6 and up still causes a high CPU load on YT video pages. I had to reinstall 5.4.5 to get it to stop.

I know it's definitely SponsorBlock 5.4.6 (and 5.4.7) because I tried disabling addons and the high-CPU only happens when SponsorBlock is active and only if it's 5.4.6 or higher.

Something in 5.4.6 is causing a high CPU load in Firefox.
