### ISSUE TITLE
Add Donation options?

### ISSUE THREAD

**Issue by inconspicuous-username** [ajayyy/SponsorBlock#184]
This plugin has made my youtube experience significantly better and more enjoyable. And if there are anymore people like me, maybe a donation button in the readme, or on the SponsorBlock popup might help cover the costs of hosting your server.

**Comment by ajayyy** [comment]
Thank you for considering this!

Right now, the server costs are still "free" for me since I am running it off an old PC of mine, but I am planning on paying for some servers soon since the server load is growing and it would be nice to have some in Europe or Asia to make SponsorBlock just as fast there as in North America.

Luckily, some generous people have already donated an amount that should cover servers costs for a bit, so I am not too worried about that. I am saving those donations for when I setup some more servers. I would rather not clutter the UI if I don't have to.

However, I'll leave this issue open for people still interested in donating.

https://www.paypal.me/ajayyy (other methods available if you contact me)

Thanks!

**Comment by phiresky** [comment]
> it would be nice to have some in Europe or Asia to make SponsorBlock just as fast there as in North America.

Only somewhat relevant, but I'm curious how are you planning on distributing the servers if the storage is a sqlite database? :)

**Comment by ajayyy** [comment]
I was going to make an API endpoint to get all new data past a certain timestamp

**Comment by phiresky** [comment]
So do you only want to distribute the read queries or also the writes? Cause then you'd need to also implement merging of votes etc which is kinda hard / annoying to do correctly.

**Comment by JetseBrouwer** [comment]
I think a simple solution would be doing the write to one main server, and then do the reads from a server that geographically close. If a write is a few milliseconds slower than reads that's not a real problem.
Reads are done way more often, and are also more critical to the user experience. 
IS it the most elegant solution, no? is it sufficient, and straight foward I think so.

**Comment by phiresky** [comment]
Yep, sounds good. The only problem is if you have reads where having current written data is needed (e.g. if you add a sponsorship, then refresh the page it looks like it disappears and will only shop up N minutes later when the read server gets the new data)

**Comment by JetseBrouwer** [comment]
That is true, although what one could do, is that if no data was found on the localized server, the request is forwarded to the 'main' server.
If the data did exist there, the local server can forward it to the end user, and then simultaneously update its local database.
It would take a bit longer, but only for very recent entries.

**Comment by phiresky** [comment]
Not sure if that's a good idea since probably like 90% of requests to the server are "not found" requests since "most" videos aren't in the database and they aren't distinguishable from recently added ones

**Comment by JetseBrouwer** [comment]
That is correct. But For what I recall is that the original goal was caching, not load balancing.
For load balancing, this would indeed not reduce the load significantly from the main server. When the goal is caching, this will most definitely succeed.
But then again, seeing this is a very common problem, there might exist an easily deploy-able solution out there.

**Comment by phiresky** [comment]
True. For just caching you could probably also just put cloudflare in front of the server and add a rule to force it to cache api responses and add a second uncached api.

> easily deploy-able solution out there.

yep, but probably not without significant architecture changes (esp. regarding sqlite3).
e.g. postgresql with one master server and replicated servers (don't even need to be synchronous, asynchronous replication is probably enough)

**Comment by ajayyy** [comment]
Just to clarify, only read queries would be spread

**Comment by ajayyy** [comment]
You guys make good points. Why go through this hassle when CloudFlare caching could achieve the same goal? Plus, it's free

**Comment by phiresky** [comment]
It might not be perfect, because cloudflare has 200 datacenters and they each cache separately. So a request will only be cached if a user in the same region has already watched the same video recently. Also purge seldom-requested data from their cache regularily so not sure how that would impact it. 

The purging API is not instantaneous (i think they say it can take up to 1 minute) and also might have rate limits not enough for the number of updates we have here. Also you need to change some settings to enable caching of requests that have parameters and stuff cause by default they only cache some file extensions. Should work in free tier as well but not sure.

**Comment by ajayyy** [comment]
From what I've read, it is near instant and there are no limits even in the free tier.

And a second server **would** be mostly load balancing. However, keeping costs as low as possible is always best, so if it can be avoided, it might as well be.

**Comment by TheFrenchGhosty** [comment]
> You guys make good points. Why go through this hassle when CloudFlare caching could achieve the same goal? Plus, it's free.
> 
> Cloudflare has an API to delete items from cache, which the server could call whenever something is published.

Please do not use Cloudflare they already have a big enough monopoly, see http://www.crimeflare.org:82/ and https://codeberg.org/crimeflare/cloudflare-tor

**Comment by ajayyy** [comment]
I get it, but it is amazing for the price (free).

**Comment by TheFrenchGhosty** [comment]
Maybe... but this price is also why they have that monopoly.

And since they are absolutely not trustworthy this is really sad that it's the case.

**Comment by whyiswhen** [comment]
paypal is closing down it's indian operation . that means indian will not be able to donate
