### ISSUE TITLE
Total skips reduced it self

### ISSUE THREAD

**Issue by Vitamin-X** [ajayyy/SponsorBlock#1843]
![Auswahl_080](https://github.com/ajayyy/SponsorBlock/assets/8036752/c6bcef32-9261-4fe1-b402-f57e0c1f8378)
![Auswahl_081](https://github.com/ajayyy/SponsorBlock/assets/8036752/dcbdbf48-207c-4fc9-b853-dafd117e4d4e)

i don't know what happen but after i clicked the reload button under the counter and i lost a couple skips from others

is that a bug or was the translation of that button wrong and it was reset and not reload?
 
didn't got the button to reappear to check again...

**Comment by ajayyy** [comment]
You can lose skips if submissions are downvoted

**Comment by Vitamin-X** [comment]
aaah i get it, thanks for telling me :)

**Comment by Vitamin-X** [comment]
i know it closed, but i just notice something...

there are many users that just dislike the part you marked to mark thier own at the exactly same time

like here https://sb.ltn.fi/video/8Bf57zWIgaY/   i marked the ad at 0:00:48.426-0:01:03.848 then it got replaced by a """VIP""" submission at the time   	0:00:48.109-0:01:03.682


so i would love to report the user NoMoreAngel ( b4ef0a7b87f16a8b18f3963d9318abda910900fd87b15d3f1da2772433e0522b ) he is clearly farming skips by downvoting skips and marking them by them self

**Comment by NoMoreAngel** [comment]
> i know it closed, but i just notice something...
> 
> there are many users that just dislike the part you marked to mark thier own at the exactly same time
> 
> like here https://sb.ltn.fi/video/8Bf57zWIgaY/ i marked the ad at 0:00:48.426-0:01:03.848 then it got replaced by a """VIP""" submission at the time 0:00:48.109-0:01:03.682
> 
> so i would love to report the user NoMoreAngel ( b4ef0a7b87f16a8b18f3963d9318abda910900fd87b15d3f1da2772433e0522b ) he is clearly farming skips by downvoting skips and marking them by them self
> 
> EDIT: just checked his other submissions and its done on like all of them EDIT2: kept checking and except 2 of my downvoted skips were all stolen by the same user

I don't know if you watched my segment and your segment right after each other, but you probably should do that. Your segment starts in 4 frames before the first frame of the sponsored content and cuts back into the video 4 frames before the actual content starts again. Both are in the middle of a transition with audio. If you listen to this audio your segment cuts weirdly. This is caused by the small delay you have when skipping. The segment only gets skipped one or two frames (depends on the browser, can be more) after the first frame of the segment but the cut back in is always directly at the specified timestamp. So in your case you are repeating two frames which leads to the weird audio behaviour.
On the other hand my segment cuts a few frames before the transition for the sponsor starts and skips that whole thing completly. The cut back in is on the first frame of the transition out of the sponsor. If you watch the video with that segment it skips like there never was a sponsor spot (and one extra transition). It is always better to skip the transition into the sponsor completly as you won't have the described timing issues that way.

So if your segment would have been without the described issue and skipped like mine, yours would have gotten an upvote and been locked by me and I wouldn't have made my segment.

**Comment by Vitamin-X** [comment]
bullshit, the video maker places an animations in the cuts, and when you match the animation befor and after,
the frame dont matters at all

but that link was a bad example just the first i notice

what do you say to that one here then https://sb.ltn.fi/video/Zn7cytPXuco/ ? when i check mine its frame perfect i dont notice any imperfection, but you downvoted it anyway and made your own
