### ISSUE TITLE
Uncaught (in promise) TypeError: can't convert undefined to object Uncaught (in promise) TIMEOUT Blank Panel

### ISSUE THREAD

**Issue by BeneAlgirdas** [ajayyy/SponsorBlock#1936]
Plugin's panel is blank. Plugin doesn't work. What is the problem?
![errors](https://github.com/ajayyy/SponsorBlock/assets/44391653/d3bd3644-b740-4052-a525-cca752a1bf3e)

**Comment by ajayyy** [comment]
What's your browser and extension version? and did you just install it?

**Comment by BeneAlgirdas** [comment]
Browser, as it can be seen from UI - Firefox. All latest versions.
Moving on, reinstall fixed that, however I almost lost my UserID. It would be perfect to know what caused that and how that should be solved, how UserID can be extracted on extension corruption like this.

**Comment by ajayyy** [comment]
This is a browser bug then, not an extension bug

**Comment by TalkLounge** [comment]
Had the same problem just now.
Seems to be a Firefox problem that sometimes Firefox is unable to write the extension data or in a corrupted format. Had enough free storage on my disk, so that was not the issue. I force quited firefox by task manager, because firefox was still running a while after closing, maybe this had caused it, but I'm not sure if that was really the reason.

Other extensions were not affected, only Sponsorblock.

Luckily I've been making backups of my browser data from time to time, so I was able to load an old browser state and restore the UserId.
