### ISSUE TITLE
[feature] Display who sponsors the video, and to promote what

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [ajayyy/SponsorBlock#2022]
The primary goal is to help making an informed decision on whether the video is biased towards its sponsor(s) or not.

The entries would be user submitted and if enabled by the user, could be displayed on the sponsor skipped notification, or somewhere near the video title.
The formatting could also be user configurable using keyword arguments, example string: `"SponsorBlock just skipped {sponsor} {promotion} promotion"`
The promotion fields should be generic, not containing any branding, i.e `smartphone` instead of `Ultra Super Duper 5`
Some examples (user submitted fields are `highlighted`):
- Sponsor: `XYZ`
  Promotion: `new smartphone`
- `XYZ` sponsored this video to promote `new smartphone lineup`.
- This video is sponsored by `XYZ` and promotes `new smartphone lineup`.

**Comment by ajayyy** [comment]
no

**Comment by PasttaTypo** [comment]
> > no
> 
> Fair enough, may I ask why not?

Because millions of submissions have been made so far without having the sponsor details added, so all of those submissions would need to be updated with added context. (Not happening.)

Sponsor segments are self-explanatory. YouTuber discusses / showcases product, SB skips it. You want to know what was skipped, just rewind and check the vid description.

**Comment by ajayyy** [comment]
The goal is for you not to see what the sponsorship was. Having the UI tell you that defeats the purpose of the extension
