### ISSUE TITLE
Preview? a segment before submitting

### ISSUE THREAD

**Issue by evd316** [ajayyy/SponsorBlock#2106]
Why preview a segment before submitting (function previewSegmentRequired)?
What's the point of this? When, for example, a video already has segments created by someone else?
That's what SponsorBlock is all about - NOT TO WATCH ADVERTISING!
When you do multiple segments in a row, seamlessly, this segment preview throws off the timing and you get a few seconds of ads between segments.
![sponsorblock3](https://github.com/user-attachments/assets/df61a2c8-532c-4541-9160-4979e557a5ec)

**Comment by evd316** [comment]
Why is this feature needed?

**Comment by FelixFourcolor** [comment]
> That's what SponsorBlock is all about - NOT TO WATCH ADVERTISING!

You're mistaken. The point is for *viewers* to not to watch ads. But as *submitters*, we make the *sacrifice* to watch ads, sometimes twice, or even at half speed, so that we can make perfect cuts for everyone else. A perfect cut is one so seamless, both visually and audibly, that no one would notice the skip. It's not humanly possible to make such cuts without previewing, hence the rule. If you don't like it, it's fine, you don't have to submit, but that's the rule for submitters.

**Comment by evd316** [comment]
@FelixFourcolor You are wrong: we are not _victims_ and not _slaves_! I am a **good submitter**. I make my contribution qualitatively (frame by frame) to "Make this world a better place", unlike some "victims" who make segments slapdash, inaccurately in time and category at random. And when I correct their mistakes after a downvote, I have to spend more time re-searching for the necessary previous frame after previewing if there are several segments with different categories in a row (UPD: This is especially inconvenient on a smartphone in ReVanced/Morphe app). That is why I am against mandatory previewing. Make mandatory previewing for those who have a low rating due to many downvotes.

How can you not understand?! Previewing does not solve the issue of quality of cutting segments. I have seen this in practice. Those who are indifferent to their contribution to the common cause, will still watch two seconds and send the segment. Why do they do this at all? It's voluntary.
@ajayyy

**Comment by chris-morgan** [comment]
This continues to bother me on the odd occasions I submit things because I forgot how bad it is.

Let me describe just *how bad* this is.

A video published a few days ago which I’m just watching now bothers me with a stupidly-long two-part introduction sequence (introduction animation slightly related to its content, then panoramic entrance sequence of absolutely no relevance to the content). I zip through it at 4× speed (a personal user script I wrote a few years ago, sets playbackRate on videos to 4 while the z key is held), displeased and reconsidering watching the video, then decide to be helpful and mark it for others’ benefit.

I return to the start, and mark two segments, choosing the appropriate start and end frames by frame-by-frame stepping: 0:00.000 to 0:09.625, and 0:09.625 to 0:35.050.

I go back to playing the video. By 1:30, I decide that it seems like the video’s being sensible for now, so I press the submit button and mark the two regions as Intermission (skip) and Tangents (skip). If it goes rogue later, I’ll submit more segments later.

But it *won’t let me submit*. Instead, it interrupts me and says “you have to preview first”.

At this point, I’m somewhere around 2:17.

Being a glutton for punishment, I press the preview button.

It takes me back to the start, plays a second or two from around 0:09.625 **because the preview doesn’t even reflect normal playback behaviour** (just as evd316 noted), and then continues at 0:35.050.

It has lost the fact that I was at 2:17; I’ll need to find my own way back there.

At least it will now let me submit. But it has reminded me why I stopped doing so, and **I am now unlikely to submit any more segments until I forget this lesson yet again**.

Seriously, this is an *absolutely horrible* misfeature for conscientious users. *You’re actively discouraging people from submitting.*

The offending lines of code: https://github.com/ajayyy/SponsorBlock/blob/4af96fe807d1040590c2aeabe9da09c553b5b57e/src/content.ts#L2472-L2473. Provided you’re using an environment where unsigned extensions are allowed, it’s not hard to find this in the built extension and patch the test out. I’m probably too lazy to do so myself; instead I’ll probably just stop contributing again, like last time this frustrated me.

Friction can improve quality, but it can also just discourage use, and I strongly suspect that’s its only effect here.

Would allowing people to opt out of requiring previews be an acceptable compromise? I’d be willing to contribute that.

**Comment by evd316** [comment]
@chris-morgan I fully support you. And as you rightly said, "it can also just discourage use"— I haven't sent any segments in a while (unfortunately, they=advertisers finally achieved their goal indirectly with your help).

**Comment by Fabian42** [comment]
(That commit message above is misleading, I did that on my own fork, not here.)

90% of my submissions are on the same podcast, which already lists the ad times in their chapter list. So I just need to copy those and paste them into SponsorBlock. Sure, they're not milliseconds-precise, but neither is yt-dlp's cutting (I think), which is what I actually care about. And nobody else submits for these usually, or only weeks later.
I already know that these segments are correct, because the podcast hosts are somewhat perfectionsts. But I am forced to preview anyway, which means:
· Because the YouTube website is incredibly laggy (one of the reasons why I usually don't use it), it ends up playing a significant portion of the ad anyway, which both makes the preview useless and also is exactly what I'm trying to avoid.
· It uses up my mobile data to download a part of the video, even though I only actually intend to download the audio.
· If it's summer where the podcast hosts live, one often puts his bare foot right towards the camera, which is about as bad as the ad itself.
· Sometimes the website even lags so much from trying to play and then pause the video again that I'm struggling to actually submit the segment.

@chris-morgan I just tested your change (by just removing the entire condition block) and it seems to work, thank you!
Such a small change was quite an effort to do, I (backed up my Firefox data and then) had to switch to Firefox dev edition, re-apply my previous profile, change a config value, check out and modify and build the extension, put all the contents of one of the folders into a zip (but not the folder itself) and then I could finally install the extension.

**Comment by ajayyy** [comment]
please do not submit rounded second submissions or remove the preview requirement from your client. Your SB account will be banned

**Comment by chris-morgan** [comment]
I’ll make one last attempt, since @ajayyy is clearly reading.

Objective truths for SponsorBlock:
1. Forcing preview *may* improve quality from some submitters, but *definitely* frustrates some people into not submitting. Three of us have reported this. It’s statistically certain there are many others like us.
2. Preview is manifestly broken (as we three have also reported): it doesn’t skip in a timely fashion, so that it cannot help to improve segment start time quality. This significantly undermines the quality argument; and even if that gets fixed, quality arguments made before the fix are still called into question.

Also one point that I missed rebutting the first time:

> It's not humanly possible to make such cuts without previewing, hence the rule.

This is just wrong. Blatantly wrong, *laughably* wrong. I imagine that quite a large fraction of segments correspond to instant cuts in the video, which can obviously be matched by framewise stepping (… though it’d be good to have clarification on [interval openness](https://en.wikipedia.org/wiki/Interval_(mathematics)#Open_and_closed_intervals), if consistency between engines exists, which it may not, hardware acceleration wreaks havoc on video stuff). You do know about <kbd>,</kbd> and <kbd>.</kbd>, right? That’s how I would always do such things myself. Or playing at 0.25× speed would often work too. If I’ve selected the appropriate frames, how is preview going to help?

And a lot of other segments have reasonable start/end windows more than half a second wide.

And a lot of segments *can’t* be as clean as described, because the segmentation is ultimately a blunt weapon.

And even if you preview, editing the number manually offers no guarantees of improvement—it wouldn’t surprise me if it sometimes makes things worse, actually. Certainly a lot of imprecisely-timed segments still get submitted. I doubt it’s possible to say whether forced preview has helped with that; it’s possible it may have.

----

A few closely-related phenomena:

- *Alert fatigue* (a.k.a. notification fatigue): you get so many alerts and notifications that you end up just ignoring them all, or missing the important ones. As W. S. Gilbert [put it](https://gsarchive.net/gondoliers/web_opera/gond16.html), “When everyone is somebodee, Then no one’s anybody!”

- *Consent fatigue* (a.k.a. permission fatigue): something’s undesirable or dangerous, so you get asked “are you sure?” After a bit, you get used to just clicking through such things; and so the prompt no longer achieves its intended purpose—it can even become worse than the previous state. Windows Vista had a huge problem with this with UAC. Cookie banners with their malicious mostly-non-compliance to ePD/GDPR have preyed on this. Browsers have struggled with it in permission prompts. Many more examples.

- Forced password rotation sounded like a good idea at first, but human nature made it a bad idea: it encouraged weak passwords and unsafe password management practices. And so these days it is recommended against.

Forced preview has these consequence:
1. Some will just click through it and ignore it, so that it does no good, but only wastes their time.
2. Since preview is broken (not skipping in a timely fashion), even those that might in theory benefit from it often can’t, so that it does no good.
3. Some get fed up and just don’t contribute, so that it does clear harm.

My conclusion: I have seen no evidence of forced preview doing *any* good, and compelling arguments that it does harm.

So I offer the compromise suggestion: allow opting out of forced preview. I’ll contribute the code myself if you’ll accept it.

(Sigh. I intended this to be three or four lines. Oops.)

**Comment by Fabian42** [comment]
> please do not submit rounded second submissions or remove the preview requirement from your client. Your SB account will be banned

I can only repeat what was already said: It doesn't cut precisely anyway, seconds precision is better than nothing, I usually cannot get the exact time and I refuse to watch an ad 5× to attempt it. If you ban me for helping, then I guess I won't help anymore.
Also, if anyone ever does care about such precision, they can just downvote my segment and submit their own.

**Comment by ajayyy** [comment]
We have high standards for submissions and would prefer no submission to an inaccurate one

**Comment by jiraph** [comment]
> 2\. Preview is manifestly broken (as we three have also reported): it doesn’t skip in a timely fashion

What do you mean by this? it seems to work exactly as expected on my end

**Comment by chris-morgan** [comment]
@jiraph Read the earlier comments. Three of us have reported the same symptoms.

**Comment by jiraph** [comment]
@chris-morgan I have, and I'm not sure what you are trying to describe. If I have a segment from 1:10.125-1:18.988, then when I press preview, it starts playing 2 seconds earlier at 1:08.125 and when it reaches 1:10.125 it skips to 1.18.988 as expected. If there is a second segment from 1:18.988-1.33.122, then previewing the first segment skips both of them at once, from 1:10.125 to 1.33.122, as expected.

**Comment by Fabian42** [comment]
Are you maybe on Chrome? I think Google does some shady stuff to make performance on YouTube worse on everything except Chrome.

**Comment by evd316** [comment]
@ajayyy Please just add the 'skip preview' functionality and/or a checkbox in Settings 'Disable mandatory preview request before sending a segment'. Make mandatory previewing, for those who have a low rating due to many downvotes, for example, in the last 30 days and for those who frequently slack off by submitting rounded-second segments.

SponsorBlock is a CROWDSOURCED project. It’s an amazing tool, but it is nothing without its submitters. We are the ones building the database and making the actual sacrifice of our time so millions of others don't have to watch ads. Forcing broken features on experienced, high-rating contributors (and not only) only causes alert fatigue and drives away the most dedicated people. Let’s treat this as a partnership, not an dictatorship. A simple karma-based checkbox for mandatory preview would solve this for everyone without lowering your quality standards.

This is a textbook example of Goodhart’s Law: "When a measure becomes a target, it ceases to be a good measure." By making previewing a hard requirement, it no longer ensures quality. Careless users will still just click through it blindly to unblock the submit button , while meticulous, frame-accurate contributors get frustrated and leave the project.

BUT:
Everyone perfectly understands that people can just blindly click through it. But if you believe that this barrier filters out those who are simply too lazy to wait a few extra seconds, and that removing this obstacle would cause a massive influx of low-effort, trashy, rounded-second submissions from random people, then OK.
