### ISSUE TITLE
Blur the sponsored fingrane or add a new category, in Sponsorblock, for sponsored sequences that are impossible to block.

### ISSUE THREAD

**Issue by gut1414** [ajayyy/SponsorBlock#2145]
This video is sponsored, at the very beginning by watermark.

https://www.youtube.com/watch?v=DsFEhxuqoC8

Content creators are competing in their imagination to force their sponsors through, while preventing us from cutting sponsored sequences.
In addition to the placement of products, logos, etc., in useful content, there is this watermark, like in this video.

In this video, at the very beginning, there is a sponsor in the form of a watermark over a certain time (30 seconds here). If someone decides to consider, and report to Sponsorblock, this sequence with the watermark, as a sponsored sequence to skip, a useful part of the video will be cut off.
We would have to find a way to blur this sequence, with an AI for example, which would detect logos, for example, but we need advanced tools, which Sponsorblock could not have, both on the client and server side.

Otherwise, we would have to invent a type category "product placement/sponsored watermark", just to warn Sponsorblock users of the presence of these sponsored sequences and that Sponsorblock is aware of this presence. Users can choose to skip these sequences or not, as is possible in Sponsorblock, with manual skips.

**Comment by mirror176** [comment]
#538 seems to be the discussion that would lead to a solution for this issue. If skipping it would have to skip content, then skipping is not yet the right solution.

If this example had been a watermark that was modifying data instead of replacing it (semi-transparent) then non-substitution techniques could be used to mathematically undo it to a degree but just replacing it would probably cause less distortion/distraction. A watermark fighting algorithm would be beneficial but likely best when preprocessing is available (like when reencoding) and would likely cause less damage to the video encoder bitrate than covering it with a box from past/future video scene or single color (unless bounds are carefully chosen to be at encoder block edges) or leaving the watermark.

**Comment by gut1414** [comment]
Your answer make sense, but, a special unblockable "intrusive" category seems good for me to warn users to presence of unwanted elements and let them to choice to watch, or not, a video.
