### ISSUE TITLE
General feedback, suggestions and design concept

### ISSUE THREAD

**Issue by Geroyuni** [ajayyy/SponsorBlock#27]
I have some thoughts about possible enhancements to the user experience which I'd like to share from using it for a while, plus a design concept which can serve as inspiration. Feel free to do whatever with this.

1. **Reskip button after unskipping**
It'd make a lot easier to check if an actual advertisement is happening if you could reskip after you clicked to unskip ('go back' button). Keep the window open for a bit more time to allow for that.

2. **Close timer - pausing/resetting it**
It'd be nice to see the time ticking down. As a bonus, that allows for you to pause time when the user hovers the screen, as you could show that visually with a pause icon (and pausing when hovering is good as it gives you some time to think).

3. **Instead of not showing at all, at least show an icon**
I'd definitely recommend having an option for a cirular icon instead of all or nothing. It lets you know that, "yes, this sudden skip was the ad being skipped", while not being as intrusive. It also gives the person a chance to click it and dislike/unskip the ad.

4. **Improve window layout, look simpler/smaller**
Below you can see my take on it, plus using the suggestions above (feel free to do whatever with that, you can copy it fully if you want). I also decided to put the window inside the player, in the top-right, as I felt the current location was awkward (and breaks in fullscreen).

![](https://files.catbox.moe/c2pxfo.png)

Regardless, I'm a big fan of this extension; it's a brilliant idea. Keep it up man

**Comment by ajayyy** [comment]
I love that design, it's amazing. As you can tell, I'm not a designer myself, just a programmer haha. It is better than the original design however.

![image](https://user-images.githubusercontent.com/12688112/61988994-33a8e380-aff7-11e9-925e-3c2d26ae2a8e.png)

I was thinking of copying the skip ad countdown from YouTube and using it as a count down to when the ad will happen. Then, this can auto skip it or just become a skip ad button maybe.

![image](https://user-images.githubusercontent.com/12688112/61989432-24c52f80-affd-11e9-8820-d7679000d4ee.png)

**Comment by Geroyuni** [comment]
That's a pretty good idea, it makes it less annoying to ensure the section is actually an ad, without needing to unskip. The skip button could then just have next to it a 'this isn't an ad' button; if they skip it shows the current pop-up setup, in case the landing end time is bad

**Comment by mirror176** [comment]
Store coordinates with the block; something basic like top left, top center, top right, etc. alone could help guarantee the notification can stay unobtrusive if not offering more advanced placement options with maybe custom popup options as some videos may be better served with a popup of wider vs taller dimensions in the decided area.

**Comment by ajayyy** [comment]
So far, the notice has been shrunk a little and moved to where the skip ad button is. A full revamp will come soon hopefully (well, when I get back, so in a week or two).

**Comment by bershanskiy** [comment]
A few random ideas:
### Please do not mimic existing YouTube UI elements, that just adds confusion
> I was thinking of copying the skip ad countdown from YouTube and using it as a count down to when the ad will happen. Then, this can auto skip it or just become a skip ad button maybe.

As a user, I would be confused if an extension's UI was indistinguishable from a site's own UI. I would like to know when the "skip" button is YouTube's own skip button (and thus can not skip a part of the video) and when it is extension's skip (and thus might be inaccurate, I might need to un-skip it). Knowing this distinction saves some amount of time during "debugging".

### Add indication of skippable segments on the scrub bar
As a user, I would like to know how many "skips" a video has and where they are located in the context of the video. The timestamps are very counterintuitive (and are hidden unless I click to open a popup or side menu). Thus I believe a bar on the video scrub bar for each skippable segment would be better. E.g., here are two slightly different designs (I'm graphically challenged, so I use Pant):
1. The yellow bar indicates a skippable segment, complete with start and end marks. If you hover on it, it reveals real timestamps, if you need them. I painted it yellow to contrast with red, grey and black, but it can be any color not used by YouTube UI.
2. The second section also has a "cross" button on it, which user can click if that segment turned out to be not a sponsored segment. The button disables skipping of that segment and might even cast "thumbs down" vote automatically.
![Untitled](https://user-images.githubusercontent.com/45960703/62588181-720d9080-b88a-11e9-8324-a67cc98b1f68.png)

### The duration of "skip warning" display should be customizable
No matter how extension communicates its intent to skip a section of the video, the duration of that warning should be customizable. E.g., someone might want to see this notification for 5 seconds, someone might want it displayed for 10 seconds to have time to move the mouse, someone (e.g., me) might want it to pop up for just a second and not obstruct the video.

**Comment by ajayyy** [comment]
![](https://cdn.discordapp.com/attachments/603643299961503761/606876505699647524/unknown.png)

This is one of the ways I was thinking of doing it and is how another similar extension does it. (See the grey lines under the seek bar)

However, I might make the color more visible

**Comment by bershanskiy** [comment]
@ajayyy What is the name of that extension?

Putting the line underneath the main line does make sense sinse it is clickable itself. Actually, I think ideally all interactive (clickable) elements should be some distance away from each other to prevent accidental misclicks.

UI designers actually have "Fitt's Law" which relates the distance a cursor needs to be moved, the size of the target area and the duration of time user takes to move the cursor. We should consider that too.

**Comment by ajayyy** [comment]
https://addons.mozilla.org/en-US/firefox/addon/videosegments/

**Comment by ajayyy** [comment]
Result:

![new notice2](https://user-images.githubusercontent.com/12688112/63067735-5a638700-bede-11e9-8147-f321b57527ec.gif)

There still can be some tweaks, but I think this is a great improvement to the current notice.

**Comment by ajayyy** [comment]
Splitting into https://github.com/ajayyy/SponsorBlock/issues/684
