### ISSUE TITLE
More fine-grained reports

### ISSUE THREAD

**Issue by Synthetica9** [ajayyy/SponsorBlock#360]
Currently, the only report that can be made is "good" or "bad". I think it would be beneficial to be able to report "early start", "late start", "early end", and "late end".

**Comment by ajayyy** [comment]
The idea is that you downvote (report) and resubmit.

However, I am adding some downvoting options in coming updates. "Incorrect timing", "Incorrect Category" (along with the category update), and "No sponsor here". The last one would vote to not show any submissions in that time period instead of just that one submission.
