### ISSUE TITLE
Category Request: Break, Intermission or Interruption

### ISSUE THREAD

**Issue by mrgreywater** [ajayyy/SponsorBlock#394]
Since twitch.tv removes old VODs it's common for streamers to reupload their livestreams to youtube instead. Those are usually unedited and therefore contain long sections when the broadcasters are on a break where basically nothing is happening except for an animation or maybe a video game menu.
Those sections don't really have a proper category in SponsorBlock yet. They would probably best fit into the "Intro" section as of now, but it doesn't really fit.
Here is an example: https://www.youtube.com/watch?v=A0GBd5AQb8Y

#383 seems related

**Comment by ajayyy** [comment]
I think "Intermission" could work. I didn't think of that work. Any suggestions on a name and concise description are appreciated.

**Comment by mirror176** [comment]
interstitial or interstice; would be more about the placement rather than the content within. May be an intermission, just the dead space mrgreywater referred to, or the transition clips between or to/from content like you find transitioning to/from a commercial break or just inbetween as a single piece where you could imagine a commercial may have been put if on tv.

**Comment by ajayyy** [comment]
I want to find something that doesn't include actually useful transition title cards. That's why I like "intermission" more.

**Comment by mrgreywater** [comment]
> Any suggestions on a name and concise description are appreciated.
Here is mine:

**Intermission** - _An interval without actual content. Could be a pause, break or a gap in the video._

**Comment by ajayyy** [comment]
Done in 2.0.3
