### ISSUE TITLE
[Suggestion] Separate Leaderboard

### ISSUE THREAD

**Issue by TurfJakkals** [ajayyy/SponsorBlock#448]
In line with issue #445 , perhaps having the option to separate, or filter VIP users from the rankings.

**Comment by DuckOfDuckness** [comment]
Worth noting: This person abused their VIP privileges to get to the top of the leader board. To my knowledge no other VIP has done this. Even after their lost their VIP privileges, they abused the system to maliciously remove correct segments by another (non-VIP) user because that user was now at the top of the leader board.

Only after they lost their VIP privileges did they start complaining about the leader board, despite themselves being the only VIP to have ever done this. The leader board is not a problem; this person is.

Keep this in mind when you consider their suggestions.

**Comment by TurfJakkals** [comment]
@DuckOfDuckness Thank you for your input regarding my issue/suggestion.

Please keep personal issues outside of professional and/or enterprise environments. Thank you.
