### ISSUE TITLE
Change default shortcuts based on locale

### ISSUE THREAD

**Issue by Mertyn** [ajayyy/SponsorBlock#616]
<kbd>Shift</kbd>+<kbd>,</kbd> is already used in YouTube for lowering the playback speed. Every time i want to slow down the speed a new segment is marked or ended in Sponsor Block.
Please choose a new shortcut for that function, so it doesn't overlap with builtin functionality anymore :)

**Comment by ajayyy** [comment]
This depends on the keyboard layout and doesn't apply to US QWERTY keyboard

**Comment by Mertyn** [comment]
Ahh okay, yeah didn't think about that :D
Hopefully a good fix for this problem can be found :)

**Comment by ajayyy** [comment]
What's your keyboard layout?

**Comment by ajayyy** [comment]
Also, if you don't know, you can change the keys for the shortcuts in the options page

**Comment by Mertyn** [comment]
> What's your keyboard layout?
I have the german QWERTZ layout.

> Also, if you don't know, you can change the keys for the shortcuts in the options page
Oh great, didnt see that yet :)

**Comment by Radler77** [comment]
Is there an option to disable/unbind the shortcuts?
I wasn't able to find such an option even though it seems to have existed at some point:
https://github.com/ajayyy/SponsorBlock/issues/147#issuecomment-528841193

**Comment by ajayyy** [comment]
No, it was replaced by the rebind

**Comment by AronHK** [comment]
I looked into this and I don't think detecting the user's keyboard layout is possible.

A solution to avoiding conflicts would be implementing proper support for multikey shortcuts. So we would know that for the default setting we can only accept the <kbd>;</kbd> character if it comes form a single key. And only accept multiple keys if the user has set it up that way.
(Plus it would be a good feature regardless. Especially if more shortcuts were to come in the future.)

I could add it, since I'm already messing around with settings.
