### ISSUE TITLE
API Not working

### ISSUE THREAD

**Issue by enes4949** [ajayyy/SponsorBlock#619]
I'm trying to make GET requests to the API but it mostly gives 404.

To reproduce:
`https://sponsor.ajay.app/api/skipSegments?videoID=SiAuAJBZuGs&categoryList=["sponsor","intro","outro","interaction","selfpromo","music_offtopic"]`
This one doesn't work.
`https://sponsor.ajay.app/api/skipSegments?videoID=mnk6gnOBYIo&categoryList=["sponsor","intro","outro","interaction","selfpromo","music_offtopic"]`
This one works.

**Comment by origeva** [comment]
You queried the endpoint with "categoryList" instead of "categories" so it didn't recognize your parameter and searched with the default category "sponsor", the first video has no sponsor segments so it returned 404.
Try:
`https://sponsor.ajay.app/api/skipSegments?videoID=SiAuAJBZuGs&categories=["sponsor","intro","outro","interaction","selfpromo","music_offtopic"]`
[link](https://sponsor.ajay.app/api/skipSegments?videoID=SiAuAJBZuGs&categories=["sponsor","intro","outro","interaction","selfpromo","music_offtopic"])
