### ISSUE TITLE
add start button to submit segment

### ISSUE THREAD

**Issue by sortmaster123** [ajayyy/SponsorBlock#880]
I'd like to add a start button to submit segment selection (similar to (End) button that's already there). It will be useful for submitting intros on channels- I usually start segment and then have to use my mouse and type zeros in the window. I know it's quite a simple feature so let me know if there's a reason this button hasn't been added there yet. I have implementation ready if it turns out to be a good idea. Here's a screenshot of what I have in mind:
![image](https://user-images.githubusercontent.com/88618371/128631776-9349de5e-41cd-43b6-a4c7-7596e2dbafc3.png)
the button after pressing sets start segment to 0:00.000

**Comment by DiogeNEETs** [comment]
Pausing the video with `Space` and hitting ` 0 `or `Home` and then clicking (Now) next to the left text field works in the meantime, as does simply typing `0` to get `0:00.000`

Tested today on this video:

https://sb.ltn.fi/video/XnoWk_XQyBY/

**Comment by eladkarako** [comment]
please re-open it. it is a required feature. first sponsor/intro is tricky and annoying to rewind. it saves 4 clicks by simply clicking start/stop and editing the start point to be 0. for videos describing the issue more clearly, including why it is so annoying to right click inside the youtube player,  
see:  https://github.com/ajayyy/SponsorBlock/issues/1166

**Comment by Wever1985** [comment]
> lazy submissions of stuff starting at 00:00:01.

I see this so often that I took the time to find this thread. It's so annoying.
Why not **round down any timestamp that is clearly intended as 0:00:00** automatically? When would you ever want a segment that is only a few milliseconds long at the very beginning?

**Comment by eladkarako** [comment]
> Why not round down

because it requires 2-3 extra actions. when you web-ext is primarily used by the mouse, users won't be happy to use the keyboard,  
submissions are vulnerary:  
everything needs to be quick, convenient and intuitive,  
with as little interaction as possible.  
if it isn't, you either get low quality submissions, or non at all,  
that's user-design pattern 101.

**Comment by eladkarako** [comment]
> Why not round down

because it requires 2-3 extra actions. when your web-ext is primarily used by the mouse, users won't be happy to use the keyboard,  
submissions are vulnerary:  
everything needs to be quick, convenient and intuitive,  
with as little interaction as possible.  
if it isn't, you either get low quality submissions, or non at all,  
that's user-design pattern 101.

**Comment by Wever1985** [comment]
> because it requires 2-3 extra actions.

I'm confused. I was talking about rounding down _existing_ timestamps in the database. How would that require any user interaction...

**Comment by mchangrh** [comment]
> > lazy submissions of stuff starting at 00:00:01.
> 
> I see this so often that I took the time to find this thread. It's so annoying. Why not **round down any existing timestamp that is clearly intended as 0:00:00** automatically? When would you ever want a segment that is only a few milliseconds long at the very beginning?

Not all segments close to 0.0 are supposed to be starting at exactly 0:0.0. This would probably cause more harm than good since good segments would have to be reverted.

the goal would be to prompt users if they are making segments that are close to 0 - see #1066

**Comment by eladkarako** [comment]
> cause more harm than good

it shouldn't be an issue,  
the button lays inside the "advanced" time editing,  
which is only accessed by those whom are already  
are after maximum precision/accuracy (probably due to a lite ocd..).

it can ease and streamline the work a lot.  
not to mention it "balances" having an end-button in the UI..

I actually did a little mod. in-here  
https://github.com/ajayyy/SponsorBlock/issues/1166

**Comment by eladkarako** [comment]
I can see the pr https://github.com/ajayyy/SponsorBlock/pull/960 closed  
but I can't find it (v4.7.1) did you decided to drop this feature eventually?

**Comment by ajayyy** [comment]
6c2ee76198d8aaa429c0f1b2cfb9644c085c059c
